// VM-2 — generate the rule re-score backfill SQL from data dumps.
//
// Why generated, not set-based SQL: transactions store no normalised-merchant
// column, and the merchant normalisation lives in TypeScript
// (lib/categorisation/normalise-merchant.ts). A set-based SQL backfill would
// have to reimplement that normaliser in SQL — exactly the drift VM-2 exists
// to eliminate. Instead this script runs the REAL shared matcher
// (planRescore → matchValueRule) over dumped rows and emits guarded,
// idempotent UPDATE statements. Precedent: scripts/reextract-portrait.ts
// (outputs SQL to stdout; never auto-applied).
//
// Usage:
//   npx tsx scripts/vm2-generate-rescore-backfill.ts <rules.json> <transactions.json> > backfill.sql
//
// rules.json:        array of value_category_rules rows
//   (id, user_id, match_type, match_value, value_category, confidence,
//    time_context, avg_amount_low, avg_amount_high, last_signal_at, ...)
// transactions.json: array of live (deleted_at IS NULL), unconfirmed
//   (value_confirmed_by_user = false) transaction rows
//   (id, user_id, description, category_id, amount, date, value_category,
//    value_confidence, prediction_source)
//
// Output statements are idempotent: every UPDATE re-checks
// value_confirmed_by_user = false, deleted_at IS NULL, and IS DISTINCT FROM
// guards, so a second application updates zero rows. The trailing snapshot
// recompute mirrors aggregateMonthSpending (same SQL as the VM-1 companion),
// scoped to the affected user-months.

import { readFileSync } from 'node:fs'
import { planRescore, type RescoreTxn } from '../src/lib/categorisation/value-rescore'
import type { ValueCategoryRule } from '../src/lib/parsers/types'

type RuleRow = ValueCategoryRule & { user_id: string }
type TxnRow = RescoreTxn & { user_id: string }

const [rulesPath, txnsPath] = process.argv.slice(2)
if (!rulesPath || !txnsPath) {
  console.error('usage: tsx scripts/vm2-generate-rescore-backfill.ts <rules.json> <transactions.json>')
  process.exit(1)
}

const rules: RuleRow[] = JSON.parse(readFileSync(rulesPath, 'utf8'))
const txns: TxnRow[] = JSON.parse(readFileSync(txnsPath, 'utf8'))

const rulesByUser = new Map<string, RuleRow[]>()
for (const r of rules) {
  const arr = rulesByUser.get(r.user_id) ?? []
  arr.push(r)
  rulesByUser.set(r.user_id, arr)
}
const txnsByUser = new Map<string, TxnRow[]>()
for (const t of txns) {
  const arr = txnsByUser.get(t.user_id) ?? []
  arr.push(t)
  txnsByUser.set(t.user_id, arr)
}

const lines: string[] = []
let totalScanned = 0
let totalUpdates = 0
const byRule = new Map<string, number>()
const affectedUserMonths = new Set<string>() // `${userId}|${YYYY-MM}`

lines.push('-- VM-2 rule re-score backfill (generated by scripts/vm2-generate-rescore-backfill.ts)')
lines.push(`-- Generated: ${new Date().toISOString()}`)
lines.push('-- Idempotent: IS DISTINCT FROM + value_confirmed_by_user=false guards on every statement.')
lines.push('')

for (const [userId, userRules] of rulesByUser) {
  const userTxns = txnsByUser.get(userId) ?? []
  if (userTxns.length === 0) continue

  const { scanned, updates } = planRescore(userTxns, userRules)
  totalScanned += scanned
  if (updates.length === 0) continue

  // Group updates sharing the same target tuple into one statement.
  const groups = new Map<string, { ids: string[]; vc: string; conf: number; src: string }>()
  for (const u of updates) {
    totalUpdates++
    byRule.set(u.ruleId, (byRule.get(u.ruleId) ?? 0) + 1)
    affectedUserMonths.add(`${userId}|${u.month}`)
    const key = `${u.value_category}|${u.value_confidence}|${u.prediction_source}`
    const g = groups.get(key) ?? { ids: [], vc: u.value_category, conf: u.value_confidence, src: u.prediction_source }
    g.ids.push(u.id)
    groups.set(key, g)
  }

  lines.push(`-- user ${userId}: ${updates.length} update(s) across ${groups.size} target tuple(s)`)
  for (const g of groups.values()) {
    lines.push(
      `UPDATE transactions SET value_category = '${g.vc}', value_confidence = ${g.conf}, prediction_source = '${g.src}'`
    )
    lines.push(`WHERE user_id = '${userId}'`)
    lines.push(`  AND id IN (${g.ids.map((id) => `'${id}'`).join(', ')})`)
    lines.push(`  AND deleted_at IS NULL AND COALESCE(value_confirmed_by_user, false) = false`)
    lines.push(
      `  AND (value_category IS DISTINCT FROM '${g.vc}' OR value_confidence IS DISTINCT FROM ${g.conf} OR prediction_source IS DISTINCT FROM '${g.src}');`
    )
  }
  lines.push('')
}

// Snapshot recompute for affected user-months — mirrors aggregateMonthSpending
// (same statement shape as the VM-1 companion), scoped to touched months.
if (affectedUserMonths.size > 0) {
  const pairs = [...affectedUserMonths]
    .sort()
    .map((um) => {
      const [u, m] = um.split('|')
      return `('${u}'::uuid, '${m}-01'::date)`
    })
  lines.push('-- Recompute spending_by_value_category for affected user-months')
  lines.push('-- (mirrors aggregateMonthSpending: income + neutral categories excluded,')
  lines.push("--  positive null-category rows skipped, non-displayable labels → 'unmapped').")
  lines.push(`WITH affected(user_id, month) AS (VALUES ${pairs.join(', ')}),`)
  lines.push(`txn AS (
  SELECT t.user_id,
         date_trunc('month', t.date)::date AS month,
         -t.amount AS delta,
         CASE
           WHEN t.value_category::text IN ('foundation','burden','investment','leak')
                AND (COALESCE(t.value_confirmed_by_user,false)
                     OR COALESCE(t.value_confidence,0) >= 0.6)
           THEN t.value_category::text
           ELSE 'unmapped'
         END AS vc
  FROM transactions t
  JOIN affected a ON a.user_id = t.user_id AND a.month = date_trunc('month', t.date)::date
  WHERE t.category_id IS DISTINCT FROM 'income'
    AND (t.category_id IS NULL OR t.category_id NOT IN ('transfers','debt_repayments','savings_investments'))
    AND NOT (t.amount > 0 AND t.category_id IS NULL)
),
agg AS (
  SELECT user_id, month, jsonb_object_agg(vc, total) AS by_vc
  FROM (SELECT user_id, month, vc, sum(delta) AS total FROM txn GROUP BY 1,2,3) s
  GROUP BY 1,2
)
UPDATE monthly_snapshots ms
SET spending_by_value_category = agg.by_vc
FROM agg
WHERE ms.user_id = agg.user_id AND ms.month = agg.month;`)
}

lines.push('')
lines.push(`-- Summary: scanned ${totalScanned} transaction(s), ${totalUpdates} update(s), ${affectedUserMonths.size} affected user-month(s).`)
lines.push(`-- Updates by rule id:`)
for (const [ruleId, n] of [...byRule.entries()].sort((a, b) => b[1] - a[1])) {
  lines.push(`--   ${ruleId}: ${n}`)
}

process.stdout.write(lines.join('\n') + '\n')
